### ISSUE TITLE
Java JIRA create error : fixVersions=Field 'fixVersions' cannot be set. It is not on the appropriate screen

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/release-manager#7]
### Issue

When we try to create an issue where se set the fix version
```
 java -jar target/uber-atlassian-1.0-SNAPSHOT.jar \
    -user 'yyyyyy' \
    -password 'xxxxxxx' \
    -cfg etc/release.yaml \
    -action create \
    -url https://issues.redhat.com
```

then we got this error
```
Exception in thread "main" RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={fixVersions=Field 'fixVersions' cannot be set. It is not on the appropriate screen, or unknown.}, errorMessages=[]}]}
        at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.claim(DelegatingPromise.java:45)
        at dev.snowdrop.jira.atlassian.Client.createIssue(Client.java:91)
        at dev.snowdrop.jira.atlassian.Client.main(Client.java:39)
Caused by: RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={fixVersions=Field 'fixVersions' cannot be set. It is not on the appropriate screen, or unknown.}, errorMessages=[]}]}
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:176)
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:170)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:49)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:10)
        at io.atlassian.util.concurrent.Promises$OfStage.lambda$fold$4(Promises.java:332)
        at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:422)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.lambda$doCompleted$0(SettableFuturePromiseHttpPromiseAsyncClient.java:37)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:61)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:129)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```
### Problem

The error seems not related at all to a technical issue but is probably due to a lack of permissions as documented [here](https://community.atlassian.com/t5/Answers-Developer-Questions/Jira-REST-client-SDK-Can-t-set-assignee-or-fixVersion/qaq-p/546460)

`The fix was to ask my company's Jira administrator to allow all users to be able to set assignees and fixVersions when they create new issues.`

**Comment by jacobdotcosta** [comment]
The *Due Date* field doesn't show on the *Edit* dialog using the bot user. We might be missing some privileges on that user.

**Comment by jacobdotcosta** [comment]
The user can create issues (check [this](https://issues.redhat.com/browse/ENTSBT-469) ) but doesn't have access to the *Due Date* field. It only belongs to the `jira-users` group, he might need some more groups.

**Comment by jacobdotcosta** [comment]
I have commented the lines that set the *dueDate* and *fixVersion* fields and the JIRA ENTSBT-470 was created. 

```
INFO: Issue ENTSBT-470 created successfully
```
@cmoulliard The problem is with setting those 2 fields, the authentication is being done correctly now.

**Comment by cmoulliard** [comment]
As the `fixVersion` field is not available during the phase to create the ticket `see https://issues.redhat.com/secure/CreateIssue.jspa`, then it should not be used but maybe when we update next the ticket

**Comment by cmoulliard** [comment]
CustomField data
```
          
          {
            id=customfield_12311240,
            name=Target
            Release,
            type=null,
            value=
          {
            "self": "https:\/\/issues.redhat.com\/rest\/api\/2\/version\/12345960",
            "id": "12345960",
            "description": "Spring Boot 2.3 Release",
            "name": "2.3.0.GA",
            "archived": false,
            "released": false,
            "releaseDate": "2020-09-14"
          }
```
